// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communicate.proto

package commProto;

public final class Communicate {
  private Communicate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface batch_requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:batch_request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 RFW_ID = 1;</code>
     * @return The rFWID.
     */
    int getRFWID();

    /**
     * <code>int32 benchType = 2;</code>
     * @return The benchType.
     */
    int getBenchType();

    /**
     * <code>int32 WrkLdMetric = 3;</code>
     * @return The wrkLdMetric.
     */
    int getWrkLdMetric();

    /**
     * <code>int32 BatchUnit = 4;</code>
     * @return The batchUnit.
     */
    int getBatchUnit();

    /**
     * <code>int32 BatchID = 5;</code>
     * @return The batchID.
     */
    int getBatchID();

    /**
     * <code>int32 BatchSize = 6;</code>
     * @return The batchSize.
     */
    int getBatchSize();
  }
  /**
   * Protobuf type {@code batch_request}
   */
  public  static final class batch_request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:batch_request)
      batch_requestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use batch_request.newBuilder() to construct.
    private batch_request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private batch_request() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new batch_request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private batch_request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              rFWID_ = input.readInt32();
              break;
            }
            case 16: {

              benchType_ = input.readInt32();
              break;
            }
            case 24: {

              wrkLdMetric_ = input.readInt32();
              break;
            }
            case 32: {

              batchUnit_ = input.readInt32();
              break;
            }
            case 40: {

              batchID_ = input.readInt32();
              break;
            }
            case 48: {

              batchSize_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return commProto.Communicate.internal_static_batch_request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return commProto.Communicate.internal_static_batch_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              commProto.Communicate.batch_request.class, commProto.Communicate.batch_request.Builder.class);
    }

    public static final int RFW_ID_FIELD_NUMBER = 1;
    private int rFWID_;
    /**
     * <code>int32 RFW_ID = 1;</code>
     * @return The rFWID.
     */
    public int getRFWID() {
      return rFWID_;
    }

    public static final int BENCHTYPE_FIELD_NUMBER = 2;
    private int benchType_;
    /**
     * <code>int32 benchType = 2;</code>
     * @return The benchType.
     */
    public int getBenchType() {
      return benchType_;
    }

    public static final int WRKLDMETRIC_FIELD_NUMBER = 3;
    private int wrkLdMetric_;
    /**
     * <code>int32 WrkLdMetric = 3;</code>
     * @return The wrkLdMetric.
     */
    public int getWrkLdMetric() {
      return wrkLdMetric_;
    }

    public static final int BATCHUNIT_FIELD_NUMBER = 4;
    private int batchUnit_;
    /**
     * <code>int32 BatchUnit = 4;</code>
     * @return The batchUnit.
     */
    public int getBatchUnit() {
      return batchUnit_;
    }

    public static final int BATCHID_FIELD_NUMBER = 5;
    private int batchID_;
    /**
     * <code>int32 BatchID = 5;</code>
     * @return The batchID.
     */
    public int getBatchID() {
      return batchID_;
    }

    public static final int BATCHSIZE_FIELD_NUMBER = 6;
    private int batchSize_;
    /**
     * <code>int32 BatchSize = 6;</code>
     * @return The batchSize.
     */
    public int getBatchSize() {
      return batchSize_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rFWID_ != 0) {
        output.writeInt32(1, rFWID_);
      }
      if (benchType_ != 0) {
        output.writeInt32(2, benchType_);
      }
      if (wrkLdMetric_ != 0) {
        output.writeInt32(3, wrkLdMetric_);
      }
      if (batchUnit_ != 0) {
        output.writeInt32(4, batchUnit_);
      }
      if (batchID_ != 0) {
        output.writeInt32(5, batchID_);
      }
      if (batchSize_ != 0) {
        output.writeInt32(6, batchSize_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rFWID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rFWID_);
      }
      if (benchType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, benchType_);
      }
      if (wrkLdMetric_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, wrkLdMetric_);
      }
      if (batchUnit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, batchUnit_);
      }
      if (batchID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, batchID_);
      }
      if (batchSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, batchSize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof commProto.Communicate.batch_request)) {
        return super.equals(obj);
      }
      commProto.Communicate.batch_request other = (commProto.Communicate.batch_request) obj;

      if (getRFWID()
          != other.getRFWID()) return false;
      if (getBenchType()
          != other.getBenchType()) return false;
      if (getWrkLdMetric()
          != other.getWrkLdMetric()) return false;
      if (getBatchUnit()
          != other.getBatchUnit()) return false;
      if (getBatchID()
          != other.getBatchID()) return false;
      if (getBatchSize()
          != other.getBatchSize()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RFW_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRFWID();
      hash = (37 * hash) + BENCHTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBenchType();
      hash = (37 * hash) + WRKLDMETRIC_FIELD_NUMBER;
      hash = (53 * hash) + getWrkLdMetric();
      hash = (37 * hash) + BATCHUNIT_FIELD_NUMBER;
      hash = (53 * hash) + getBatchUnit();
      hash = (37 * hash) + BATCHID_FIELD_NUMBER;
      hash = (53 * hash) + getBatchID();
      hash = (37 * hash) + BATCHSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getBatchSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static commProto.Communicate.batch_request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static commProto.Communicate.batch_request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static commProto.Communicate.batch_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static commProto.Communicate.batch_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static commProto.Communicate.batch_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static commProto.Communicate.batch_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static commProto.Communicate.batch_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static commProto.Communicate.batch_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static commProto.Communicate.batch_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static commProto.Communicate.batch_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static commProto.Communicate.batch_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static commProto.Communicate.batch_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(commProto.Communicate.batch_request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code batch_request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:batch_request)
        commProto.Communicate.batch_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return commProto.Communicate.internal_static_batch_request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return commProto.Communicate.internal_static_batch_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                commProto.Communicate.batch_request.class, commProto.Communicate.batch_request.Builder.class);
      }

      // Construct using commProto.Communicate.batch_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rFWID_ = 0;

        benchType_ = 0;

        wrkLdMetric_ = 0;

        batchUnit_ = 0;

        batchID_ = 0;

        batchSize_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return commProto.Communicate.internal_static_batch_request_descriptor;
      }

      @java.lang.Override
      public commProto.Communicate.batch_request getDefaultInstanceForType() {
        return commProto.Communicate.batch_request.getDefaultInstance();
      }

      @java.lang.Override
      public commProto.Communicate.batch_request build() {
        commProto.Communicate.batch_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public commProto.Communicate.batch_request buildPartial() {
        commProto.Communicate.batch_request result = new commProto.Communicate.batch_request(this);
        result.rFWID_ = rFWID_;
        result.benchType_ = benchType_;
        result.wrkLdMetric_ = wrkLdMetric_;
        result.batchUnit_ = batchUnit_;
        result.batchID_ = batchID_;
        result.batchSize_ = batchSize_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof commProto.Communicate.batch_request) {
          return mergeFrom((commProto.Communicate.batch_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(commProto.Communicate.batch_request other) {
        if (other == commProto.Communicate.batch_request.getDefaultInstance()) return this;
        if (other.getRFWID() != 0) {
          setRFWID(other.getRFWID());
        }
        if (other.getBenchType() != 0) {
          setBenchType(other.getBenchType());
        }
        if (other.getWrkLdMetric() != 0) {
          setWrkLdMetric(other.getWrkLdMetric());
        }
        if (other.getBatchUnit() != 0) {
          setBatchUnit(other.getBatchUnit());
        }
        if (other.getBatchID() != 0) {
          setBatchID(other.getBatchID());
        }
        if (other.getBatchSize() != 0) {
          setBatchSize(other.getBatchSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        commProto.Communicate.batch_request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (commProto.Communicate.batch_request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int rFWID_ ;
      /**
       * <code>int32 RFW_ID = 1;</code>
       * @return The rFWID.
       */
      public int getRFWID() {
        return rFWID_;
      }
      /**
       * <code>int32 RFW_ID = 1;</code>
       * @param value The rFWID to set.
       * @return This builder for chaining.
       */
      public Builder setRFWID(int value) {
        
        rFWID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 RFW_ID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRFWID() {
        
        rFWID_ = 0;
        onChanged();
        return this;
      }

      private int benchType_ ;
      /**
       * <code>int32 benchType = 2;</code>
       * @return The benchType.
       */
      public int getBenchType() {
        return benchType_;
      }
      /**
       * <code>int32 benchType = 2;</code>
       * @param value The benchType to set.
       * @return This builder for chaining.
       */
      public Builder setBenchType(int value) {
        
        benchType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 benchType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBenchType() {
        
        benchType_ = 0;
        onChanged();
        return this;
      }

      private int wrkLdMetric_ ;
      /**
       * <code>int32 WrkLdMetric = 3;</code>
       * @return The wrkLdMetric.
       */
      public int getWrkLdMetric() {
        return wrkLdMetric_;
      }
      /**
       * <code>int32 WrkLdMetric = 3;</code>
       * @param value The wrkLdMetric to set.
       * @return This builder for chaining.
       */
      public Builder setWrkLdMetric(int value) {
        
        wrkLdMetric_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 WrkLdMetric = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWrkLdMetric() {
        
        wrkLdMetric_ = 0;
        onChanged();
        return this;
      }

      private int batchUnit_ ;
      /**
       * <code>int32 BatchUnit = 4;</code>
       * @return The batchUnit.
       */
      public int getBatchUnit() {
        return batchUnit_;
      }
      /**
       * <code>int32 BatchUnit = 4;</code>
       * @param value The batchUnit to set.
       * @return This builder for chaining.
       */
      public Builder setBatchUnit(int value) {
        
        batchUnit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 BatchUnit = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchUnit() {
        
        batchUnit_ = 0;
        onChanged();
        return this;
      }

      private int batchID_ ;
      /**
       * <code>int32 BatchID = 5;</code>
       * @return The batchID.
       */
      public int getBatchID() {
        return batchID_;
      }
      /**
       * <code>int32 BatchID = 5;</code>
       * @param value The batchID to set.
       * @return This builder for chaining.
       */
      public Builder setBatchID(int value) {
        
        batchID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 BatchID = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchID() {
        
        batchID_ = 0;
        onChanged();
        return this;
      }

      private int batchSize_ ;
      /**
       * <code>int32 BatchSize = 6;</code>
       * @return The batchSize.
       */
      public int getBatchSize() {
        return batchSize_;
      }
      /**
       * <code>int32 BatchSize = 6;</code>
       * @param value The batchSize to set.
       * @return This builder for chaining.
       */
      public Builder setBatchSize(int value) {
        
        batchSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 BatchSize = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchSize() {
        
        batchSize_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:batch_request)
    }

    // @@protoc_insertion_point(class_scope:batch_request)
    private static final commProto.Communicate.batch_request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new commProto.Communicate.batch_request();
    }

    public static commProto.Communicate.batch_request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<batch_request>
        PARSER = new com.google.protobuf.AbstractParser<batch_request>() {
      @java.lang.Override
      public batch_request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new batch_request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<batch_request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<batch_request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public commProto.Communicate.batch_request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface batch_ansOrBuilder extends
      // @@protoc_insertion_point(interface_extends:batch_ans)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 RFW_ID = 1;</code>
     * @return The rFWID.
     */
    int getRFWID();

    /**
     * <code>int32 last_Batch_ID = 2;</code>
     * @return The lastBatchID.
     */
    int getLastBatchID();

    /**
     * <code>string samples_Requested = 3;</code>
     * @return The samplesRequested.
     */
    java.lang.String getSamplesRequested();
    /**
     * <code>string samples_Requested = 3;</code>
     * @return The bytes for samplesRequested.
     */
    com.google.protobuf.ByteString
        getSamplesRequestedBytes();
  }
  /**
   * Protobuf type {@code batch_ans}
   */
  public  static final class batch_ans extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:batch_ans)
      batch_ansOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use batch_ans.newBuilder() to construct.
    private batch_ans(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private batch_ans() {
      samplesRequested_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new batch_ans();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private batch_ans(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              rFWID_ = input.readInt32();
              break;
            }
            case 16: {

              lastBatchID_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              samplesRequested_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return commProto.Communicate.internal_static_batch_ans_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return commProto.Communicate.internal_static_batch_ans_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              commProto.Communicate.batch_ans.class, commProto.Communicate.batch_ans.Builder.class);
    }

    public static final int RFW_ID_FIELD_NUMBER = 1;
    private int rFWID_;
    /**
     * <code>int32 RFW_ID = 1;</code>
     * @return The rFWID.
     */
    public int getRFWID() {
      return rFWID_;
    }

    public static final int LAST_BATCH_ID_FIELD_NUMBER = 2;
    private int lastBatchID_;
    /**
     * <code>int32 last_Batch_ID = 2;</code>
     * @return The lastBatchID.
     */
    public int getLastBatchID() {
      return lastBatchID_;
    }

    public static final int SAMPLES_REQUESTED_FIELD_NUMBER = 3;
    private volatile java.lang.Object samplesRequested_;
    /**
     * <code>string samples_Requested = 3;</code>
     * @return The samplesRequested.
     */
    public java.lang.String getSamplesRequested() {
      java.lang.Object ref = samplesRequested_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        samplesRequested_ = s;
        return s;
      }
    }
    /**
     * <code>string samples_Requested = 3;</code>
     * @return The bytes for samplesRequested.
     */
    public com.google.protobuf.ByteString
        getSamplesRequestedBytes() {
      java.lang.Object ref = samplesRequested_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        samplesRequested_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rFWID_ != 0) {
        output.writeInt32(1, rFWID_);
      }
      if (lastBatchID_ != 0) {
        output.writeInt32(2, lastBatchID_);
      }
      if (!getSamplesRequestedBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, samplesRequested_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rFWID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rFWID_);
      }
      if (lastBatchID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lastBatchID_);
      }
      if (!getSamplesRequestedBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, samplesRequested_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof commProto.Communicate.batch_ans)) {
        return super.equals(obj);
      }
      commProto.Communicate.batch_ans other = (commProto.Communicate.batch_ans) obj;

      if (getRFWID()
          != other.getRFWID()) return false;
      if (getLastBatchID()
          != other.getLastBatchID()) return false;
      if (!getSamplesRequested()
          .equals(other.getSamplesRequested())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RFW_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRFWID();
      hash = (37 * hash) + LAST_BATCH_ID_FIELD_NUMBER;
      hash = (53 * hash) + getLastBatchID();
      hash = (37 * hash) + SAMPLES_REQUESTED_FIELD_NUMBER;
      hash = (53 * hash) + getSamplesRequested().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static commProto.Communicate.batch_ans parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static commProto.Communicate.batch_ans parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static commProto.Communicate.batch_ans parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static commProto.Communicate.batch_ans parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static commProto.Communicate.batch_ans parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static commProto.Communicate.batch_ans parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static commProto.Communicate.batch_ans parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static commProto.Communicate.batch_ans parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static commProto.Communicate.batch_ans parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static commProto.Communicate.batch_ans parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static commProto.Communicate.batch_ans parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static commProto.Communicate.batch_ans parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(commProto.Communicate.batch_ans prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code batch_ans}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:batch_ans)
        commProto.Communicate.batch_ansOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return commProto.Communicate.internal_static_batch_ans_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return commProto.Communicate.internal_static_batch_ans_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                commProto.Communicate.batch_ans.class, commProto.Communicate.batch_ans.Builder.class);
      }

      // Construct using commProto.Communicate.batch_ans.newBuilder()
      public Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rFWID_ = 0;

        lastBatchID_ = 0;

        samplesRequested_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return commProto.Communicate.internal_static_batch_ans_descriptor;
      }

      @java.lang.Override
      public commProto.Communicate.batch_ans getDefaultInstanceForType() {
        return commProto.Communicate.batch_ans.getDefaultInstance();
      }

      @java.lang.Override
      public commProto.Communicate.batch_ans build() {
        commProto.Communicate.batch_ans result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public commProto.Communicate.batch_ans buildPartial() {
        commProto.Communicate.batch_ans result = new commProto.Communicate.batch_ans(this);
        result.rFWID_ = rFWID_;
        result.lastBatchID_ = lastBatchID_;
        result.samplesRequested_ = samplesRequested_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof commProto.Communicate.batch_ans) {
          return mergeFrom((commProto.Communicate.batch_ans)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(commProto.Communicate.batch_ans other) {
        if (other == commProto.Communicate.batch_ans.getDefaultInstance()) return this;
        if (other.getRFWID() != 0) {
          setRFWID(other.getRFWID());
        }
        if (other.getLastBatchID() != 0) {
          setLastBatchID(other.getLastBatchID());
        }
        if (!other.getSamplesRequested().isEmpty()) {
          samplesRequested_ = other.samplesRequested_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        commProto.Communicate.batch_ans parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (commProto.Communicate.batch_ans) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int rFWID_ ;
      /**
       * <code>int32 RFW_ID = 1;</code>
       * @return The rFWID.
       */
      public int getRFWID() {
        return rFWID_;
      }
      /**
       * <code>int32 RFW_ID = 1;</code>
       * @param value The rFWID to set.
       * @return This builder for chaining.
       */
      public Builder setRFWID(int value) {
        
        rFWID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 RFW_ID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRFWID() {
        
        rFWID_ = 0;
        onChanged();
        return this;
      }

      private int lastBatchID_ ;
      /**
       * <code>int32 last_Batch_ID = 2;</code>
       * @return The lastBatchID.
       */
      public int getLastBatchID() {
        return lastBatchID_;
      }
      /**
       * <code>int32 last_Batch_ID = 2;</code>
       * @param value The lastBatchID to set.
       * @return This builder for chaining.
       */
      public Builder setLastBatchID(int value) {
        
        lastBatchID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 last_Batch_ID = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastBatchID() {
        
        lastBatchID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object samplesRequested_ = "";
      /**
       * <code>string samples_Requested = 3;</code>
       * @return The samplesRequested.
       */
      public java.lang.String getSamplesRequested() {
        java.lang.Object ref = samplesRequested_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          samplesRequested_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string samples_Requested = 3;</code>
       * @return The bytes for samplesRequested.
       */
      public com.google.protobuf.ByteString
          getSamplesRequestedBytes() {
        java.lang.Object ref = samplesRequested_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          samplesRequested_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string samples_Requested = 3;</code>
       * @param value The samplesRequested to set.
       * @return This builder for chaining.
       */
      public Builder setSamplesRequested(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        samplesRequested_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string samples_Requested = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSamplesRequested() {
        
        samplesRequested_ = getDefaultInstance().getSamplesRequested();
        onChanged();
        return this;
      }
      /**
       * <code>string samples_Requested = 3;</code>
       * @param value The bytes for samplesRequested to set.
       * @return This builder for chaining.
       */
      public Builder setSamplesRequestedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        samplesRequested_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:batch_ans)
    }

    // @@protoc_insertion_point(class_scope:batch_ans)
    private static final commProto.Communicate.batch_ans DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new commProto.Communicate.batch_ans();
    }

    public static commProto.Communicate.batch_ans getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<batch_ans>
        PARSER = new com.google.protobuf.AbstractParser<batch_ans>() {
      @java.lang.Override
      public batch_ans parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new batch_ans(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<batch_ans> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<batch_ans> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public commProto.Communicate.batch_ans getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_batch_request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_batch_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_batch_ans_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_batch_ans_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021communicate.proto\"~\n\rbatch_request\022\016\n\006" +
      "RFW_ID\030\001 \001(\005\022\021\n\tbenchType\030\002 \001(\005\022\023\n\013WrkLd" +
      "Metric\030\003 \001(\005\022\021\n\tBatchUnit\030\004 \001(\005\022\017\n\007Batch" +
      "ID\030\005 \001(\005\022\021\n\tBatchSize\030\006 \001(\005\"M\n\tbatch_ans" +
      "\022\016\n\006RFW_ID\030\001 \001(\005\022\025\n\rlast_Batch_ID\030\002 \001(\005\022" +
      "\031\n\021samples_Requested\030\003 \001(\t2.\n\005batch\022%\n\007B" +
      "atcher\022\016.batch_request\032\n.batch_ansB\013\n\tco" +
      "mmProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_batch_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_batch_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_batch_request_descriptor,
        new java.lang.String[] { "RFWID", "BenchType", "WrkLdMetric", "BatchUnit", "BatchID", "BatchSize", });
    internal_static_batch_ans_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_batch_ans_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_batch_ans_descriptor,
        new java.lang.String[] { "RFWID", "LastBatchID", "SamplesRequested", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
